version: '3.4'

networks:
  dev:
    driver: bridge

services:
  testtaskdb:
    container_name: tt_postgres
    image: postgres:15.1-alpine
    environment:
        POSTGRES_DB: "TestTaskDB"
        POSTGRES_USER: "user"
        POSTGRES_PASSWORD: "qwerty"
    ports:
        - "5433:5432"
    restart: "always"


  testtask:
    container_name: tt_aspnetcore
    image: testtask
    depends_on:
      - "testtaskdb"
    build:
      context: .
      dockerfile: TestTask/Dockerfile
    ports:
        - "5000:80" 
